/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_japaneseverbquery_util_ImageJNIBridge.h>
/* Header for class com_japaneseverbquery_util_ImageJNIBridge */
#include <android/bitmap.h>
#include <stdlib.h>
#include <string.h>

JNIEXPORT void JNICALL Java_com_japaneseverbquery_util_ImageJNIBridge_getImageFirstSample
        (JNIEnv *env, jobject clz, jobject img, jobject result) {
    void *bitmapPixels;
    AndroidBitmapInfo info;
    AndroidBitmap_getInfo(env, img, &info);
    uint32_t count = info.height * info.stride;
    void *pxl = malloc(count);
    if (AndroidBitmap_lockPixels(env, img, &bitmapPixels) < 0) {
        return;
    }
    memcpy(pxl, bitmapPixels, count);
    AndroidBitmap_unlockPixels(env, img);

    void *address = (*env)->GetDirectBufferAddress(env, result);
    jlong cap = (*env)->GetDirectBufferCapacity(env, result);
    uint32_t mark = 0xFEDC4321;
    memcpy(address, pxl, (size_t) cap);
    memcpy(address, &mark, 4);
    if (((uint32_t *) pxl)[0] == 0xFF00FF00) {
        mark = 0xFEDC4322;
        memcpy(address, &mark, 4);
    }

    free(pxl);
    return;

}
