/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_japaneseverbquery_util_ImageJNIBridge */

#ifndef _Included_com_japaneseverbquery_util_ImageJNIBridge
#define _Included_com_japaneseverbquery_util_ImageJNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_japaneseverbquery_util_ImageJNIBridge
 * Method:    getImageFirstSample
 * Signature: (Landroid/graphics/Bitmap;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_japaneseverbquery_util_ImageJNIBridge_getImageFirstSample
  (JNIEnv * env, jobject clz, jobject img, jobject result);

#ifdef __cplusplus
}
#endif
#endif
